# Generated by Django 5.1.3 on 2024-11-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('ship_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('capcity', models.IntegerField()),
                ('max_capcity', models.IntegerField()),
            ],
        ),
    ]
