version: "2.2"

services:

  nginx:
    image: nginx 
    volumes:
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server/static:/var/www/html/static
      - ./frontend/dist:/usr/share/nginx/html
      - www-html:/var/www/html
    ports:
      - 80:80/tcp
    restart: unless-stopped
    depends_on:
      - backend 
      - frontend 
    networks:
      - web_nt 

  backend:
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    build: 
      context: ./server
      dockerfile: Dockerfile.local
    command: >
      bash -c "./manage.sh makemigrations 
      && ./manage.sh migrate"
    ports:
      - '8000:8000'
    depends_on:
      - database 
    networks:
        - web_nt 

  database:
    image: postgres:17
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
        - web_nt 

  redis:
    image: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
        - web_nt 

  frontend:
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - web_nt 

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   command: 
  #     - "http"
  #     - "--url=${NGROK_URL}"
  #     - "backend:8000"
  #   environment:
  #     NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
  #   ports:
  #     - 4040:4040
  #   networks:
  #       - web_nt 

volumes:
  static:
  www-html:

networks:
  web_nt:
    name: web_nt
