# Generated by Django 5.1.3 on 2024-11-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
        ('user', '0002_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertravelhistory',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to='ship.ship', verbose_name='Корабль'),
        ),
    ]
