# Generated by Django 5.1.3 on 2024-11-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('captain_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('surname', models.CharField(blank=True, max_length=64, null=True)),
                ('lastname', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('hash_password', models.CharField(max_length=256)),
                ('rate', models.IntegerField(default=50)),
            ],
        ),
    ]
