# Generated by Django 5.1.3 on 2024-11-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captain', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captain',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
