# Generated by Django 5.1.3 on 2024-11-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captain', '0003_rename_phone_captain_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captain',
            old_name='captain_id',
            new_name='id',
        ),
    ]
