# Generated by Django 5.1.3 on 2024-11-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bertch',
            fields=[
                ('bertch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=256)),
                ('ship_capasity', models.PositiveSmallIntegerField(default=0)),
                ('max_ship_capasity', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
